version: '3.8'
services:
  web:
    build: .
    container_name: static_web
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - net
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    env_file: .env
    restart: unless-stopped
    command: tunnel run
    networks:
      - net
networks:
  net:
    driver: bridge